### ISSUE TITLE
Feedback - Week 12 Assignment

### ISSUE THREAD

**Issue by ntuvera** [ibaena/zoo#1]
Visit all function asks for a type? code is right, but added prompt because?

Hey @ibaena, Good work on the Zoo App homework.  I cloned the repo and started checking the functionality.  

Not really a bug, but is there a reason you're prompting under the View All function?  Also, I did run into a few errors, but they look like mostly typos (ln 84 and ln 91).  You can fix those when you have time, but your overall functionality and understanding seems solid to me.

I'm only nitpicking above because you're doing well.  One more heads up, I hope you don't use your mysql password for more serious things.  I guess the random tip I can give you is with your if/else if/else statements.  Would .touppercase() on your prompt results make sense?  Given how some users interact with things, they'll try just 'q' instead of 'Q' and then something won't work.  It's silly, but users do silly things so sometimes accounting for that will help you out from people saying somethign doesn't work.

**Comment by ibaena** [comment]
Hey yeah thanks i totally forgot to exclude the pwd thanks!
